routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DeviceController;
use App\Http\Controllers\ModbusController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/slider', [DashboardController::class, 'slider'])->name('slider');

    Route::get('/setting', [DashboardController::class, 'setting'])->name('setting')->middleware('admin');
    Route::post('/setting/{secret_key:id}', [DashboardController::class, 'updateSetting'])->name('setting.update')->middleware('admin');
    Route::get('/access-viewer', [DashboardController::class, 'access'])->name('access.viewer')->middleware('admin');
    Route::get('/access-create', [DashboardController::class, 'createAccess'])->name('access.create')->middleware('admin');
    Route::post('/access-store', [DashboardController::class, 'storeAccess'])->name('access.store')->middleware('admin');
    Route::get('/access-edit/{id}', [DashboardController::class, 'editAccess'])->name('access.edit')->middleware('admin');
    Route::get('/profile', [DashboardController::class, 'profile'])->name('profile');
    Route::post('/profile', [DashboardController::class, 'updateProfile'])->name('profile.update');

    Route::get('/chart', [DashboardController::class, 'chart'])->name('chart');
    Route::get('/view-data', [DashboardController::class, 'grafik'])->name('grafik');

    Route::get('/history', [DashboardController::class, 'history'])->name('history');
    Route::get('/export', [DashboardController::class, 'export'])->name('export');

    Route::resource('user', UserController::class)->middleware('admin');
    Route::get('/device/{device:id}/grafik', [DeviceController::class, 'grafik'])->name('device.grafik');
    Route::get('/device/{device:id}/reset', [DeviceController::class, 'reset'])->name('device.reset');
    Route::resource('device', DeviceController::class);

    Route::post('/modbus/merge', [ModbusController::class, 'merge'])->name('modbus.merge')->middleware('admin');
    Route::post('/merge/{merge:id}', [ModbusController::class, 'deleteMerge'])->name('merge.delete')->middleware('admin');

    Route::get('/get-device', [DeviceController::class, 'get']);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'level',
        'image',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function devices()
    {
        return $this->belongsToMany(Device::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class UserController extends Controller
{
    public function index()
    {
        $users = User::get();

        return view('user.index', compact('users'));
    }

    public function create()
    {
        $user = new User();
        $action = route('user.store');
        $act = 'create';

        return view('user.form', compact('user', 'action', 'act'));
    }

    public function store(Request $request)
    {
        $attr = $request->validate([
            'name' => 'required|string',
            'email' => 'required|string|unique:users',
            'password' => 'required|string',
            'level' => 'required|string',
            'image' => 'required|mimes:jpg,jpeg,png',
        ]);

        try {
            DB::beginTransaction();

            $image = $request->file('image');
            $attr['image'] = $image->storeAs('images/user', Str::slug($request->name) . '-' . rand(1000, 9999) . '.' . $image->extension());

            $attr['password'] = bcrypt($request->password);

            User::create($attr);

            DB::commit();

            return redirect()->route('user.index')->with('success', 'User successfully created');
        } catch (\Throwable $th) {
            return back()->with('error', $th->getMessage());
        }
    }

    public function show(User $user)
    {
        //
    }

    public function edit(User $user)
    {
        $action = route('user.update', $user->id);
        $act = 'edit';

        return view('user.form', compact('user', 'action', 'act'));
    }

    public function update(Request $request, User $user)
    {
        $attr = $request->validate([
            'name' => 'required|string',
            'email' => 'required|string|unique:users,email,' . $user->id,
            'level' => 'required|string',
            'image' => 'mimes:jpg,jpeg,png',
        ]);

        try {
            DB::beginTransaction();

            if ($request->file('image')) {
                Storage::delete($user->image);
                $image = $request->file('image');
                $attr['image'] = $image->storeAs('images/user', Str::slug($request->name) . '-' . rand(1000, 9999) . '.' . $image->extension());
            } else {
                $attr['image'] = $user->image;
            }

            if ($request->password) {
                $attr['password'] = bcrypt($request->password);
            } else {
                $attr['password'] = $user->password;
            }

            $user->update($attr);

            DB::commit();

            return redirect()->route('user.index')->with('success', 'User successfully updated');
        } catch (\Throwable $th) {
            return back()->with('error', $th->getMessage());
        }
    }

    public function destroy(User $user)
    {
        try {
            DB::beginTransaction();

            Storage::delete($user->image);
            $user->delete();

            DB::commit();

            return redirect()->route('user.index')->with('success', 'User successfully deleted');
        } catch (\Throwable $th) {
            return back()->with('error', $th->getMessage());
        }
    }
}

resources/views/user/form.blade.php
@extends('layouts.master', ['title' => $act == 'create' ? 'Create User' : 'Edit User'])

@section('content')
<div class="row">
    <div class="col-md-12">
        @if($act == 'create')
        <h2 class="mb-3 lh-sm">Create User</h2>
        @else
        <h2 class="mb-3 lh-sm">Edit User</h2>
        @endif

        <form action="{{ $action }}" method="post" enctype="multipart/form-data">
            @if($act == 'edit')
            @method('PATCH')
            @endif
            @csrf

            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name" id="name" class="form-control" value="{{ $user->name ?? old('name') }}">

                @error('name')
                <small class="text-danger">{{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email" id="email" class="form-control" value="{{ $user->email ?? old('email') }}">

                @error('email')
                <small class="text-danger">{{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" id="password" class="form-control" value="{{ old('password') }}">

                @error('password')
                <small class="text-danger">{{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="level">Level</label>
                <select name="level" id="level" class="form-control">
                    <option disabled selected>-- Select Level --</option>
                    <option {{ $user->level == 'Admin' ? 'selected' : '' }} value="Admin">Admin</option>
                    <option {{ $user->level == 'Viewer' ? 'selected' : '' }} value="Viewer">Viewer</option>
                </select>

                @error('level')
                <small class="text-danger">{{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="image">Image</label>
                <input type="file" name="image" id="image" class="form-control" value="{{ $user->image ?? old('image') }}">

                @error('image')
                <small class="text-danger">{{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-success mt-3">Submit</button>
            </div>
        </form>
    </div>
</div>
@stop

resources/views/user/index.blade.php
@extends('layouts.master', ['title' => 'Data User'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <h2 class="mb-3 lh-sm">Data User</h2>

        <div id="tableExample2" data-list='{"valueNames":["no","image","name","email","level", "action"],"page":10,"pagination":true}'>

            <a href="{{ route('user.create') }}" class="btn btn-sm btn-success mb-3">Add User</a>

            <div class="table-responsive scrollbar">
                <table class="table table-bordered table-striped fs--1 mb-0">
                    <thead class="bg-200 text-900">
                        <tr>
                            <th class="sort" data-sort="no">No</th>
                            <th class="sort" data-sort="image">Image</th>
                            <th class="sort" data-sort="name">Name</th>
                            <th class="sort" data-sort="email">Email</th>
                            <th class="sort" data-sort="level">Level</th>
                            <th class="sort" data-sort="action">Action</th>
                        </tr>
                    </thead>
                    <tbody class="list">
                        @foreach($users as $user)
                        <tr>
                            <td class="no">{{ $loop->iteration }}</td>
                            <td class="image">
                                <div class="avatar avatar-xl avatar-bordered me-4">
                                    <img class="rounded-circle" src="{{ asset('storage/' . $user->image) }}" alt="">
                                </div>
                            </td>
                            <td class="name">{{ $user->name }}</td>
                            <td class="email">{{ $user->email }}</td>
                            <td class="level">{{ $user->level }}</td>
                            <td class="action">
                                <a href="{{ route('user.edit', $user->id) }}" class="btn btn-sm btn-info mr-2"><i class="fas fa-edit"></i></a>

                                <form action="{{ route('user.destroy', $user->id) }}" method="post" style="display: inline;">
                                    @method('DELETE')
                                    @csrf

                                    <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure delete this data?')"><i class="fas fa-trash"></i></button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="d-flex justify-content-center mt-3">
                <button class="btn btn-sm btn-falcon-default me-1" type="button" title="Previous" data-list-pagination="prev"><span class="fas fa-chevron-left"></span></button>
                <ul class="pagination mb-0"></ul>
                <button class="btn btn-sm btn-falcon-default ms-1" type="button" title="Next" data-list-pagination="next"><span class="fas fa-chevron-right"></span></button>
            </div>
        </div>
    </div>
</div>
@stop