routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DeviceController;
use App\Http\Controllers\ModbusController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/slider', [DashboardController::class, 'slider'])->name('slider');

    Route::get('/setting', [DashboardController::class, 'setting'])->name('setting')->middleware('admin');
    Route::post('/setting/{secret_key:id}', [DashboardController::class, 'updateSetting'])->name('setting.update')->middleware('admin');
    Route::get('/access-viewer', [DashboardController::class, 'access'])->name('access.viewer')->middleware('admin');
    Route::get('/access-create', [DashboardController::class, 'createAccess'])->name('access.create')->middleware('admin');
    Route::post('/access-store', [DashboardController::class, 'storeAccess'])->name('access.store')->middleware('admin');
    Route::get('/access-edit/{id}', [DashboardController::class, 'editAccess'])->name('access.edit')->middleware('admin');
    Route::get('/profile', [DashboardController::class, 'profile'])->name('profile');
    Route::post('/profile', [DashboardController::class, 'updateProfile'])->name('profile.update');

    Route::get('/chart', [DashboardController::class, 'chart'])->name('chart');
    Route::get('/view-data', [DashboardController::class, 'grafik'])->name('grafik');

    Route::get('/history', [DashboardController::class, 'history'])->name('history');
    Route::get('/export', [DashboardController::class, 'export'])->name('export');

    Route::resource('user', UserController::class)->middleware('admin');
    Route::get('/device/{device:id}/grafik', [DeviceController::class, 'grafik'])->name('device.grafik');
    Route::get('/device/{device:id}/reset', [DeviceController::class, 'reset'])->name('device.reset');
    Route::resource('device', DeviceController::class);

    Route::post('/modbus/merge', [ModbusController::class, 'merge'])->name('modbus.merge')->middleware('admin');
    Route::post('/merge/{merge:id}', [ModbusController::class, 'deleteMerge'])->name('merge.delete')->middleware('admin');

    Route::get('/get-device', [DeviceController::class, 'get']);
});

app/Models/Device.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Device extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function modbuses()
    {
        return $this->hasMany(Modbus::class);
    }

    public function digitalInputs()
    {
        return $this->hasMany(DigitalInput::class);
    }

    public function histories()
    {
        return $this->hasMany(History::class);
    }

    public function merges()
    {
        return $this->hasMany(Merge::class);
    }

    public function users()
    {
        return $this->hasMany(User::class);
    }
}

app/Http/Controllers/DeviceController.php
<?php

namespace App\Http\Controllers;

set_time_limit(512);

use App\Models\Device;
use App\Models\DigitalInput;
use App\Models\History;
use App\Models\Merge;
use App\Models\Modbus;
use App\Models\SecretKey;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class DeviceController extends Controller
{

    public function index()
    {
        $this->middleware('admin');

        $devices = Device::get();

        return view('device.index', compact('devices'));
    }

    public function create()
    {
        $this->middleware('admin');

        $device = new Device();
        $action = route('device.store');
        $act = 'create';

        return view('device.form', compact('device', 'action', 'act'));
    }

    public function store(Request $request)
    {
        $this->middleware('admin');

        $attr = $request->validate([
            'name' => 'required|string',
            'end_user' => 'required|string',
            'iddev' => 'required|unique:devices',
            'type' => 'required|string',
            'power' => 'required|string',
            'flow' => 'required|string',
            'head' => 'required|string',
            'modbus' => 'required|string',
            'digital' => 'required|string',
            'lat' => 'required|string',
            'long' => 'required|string',
            'image' => 'required|mimes:jpg,jpeg,png',
        ]);

        try {
            DB::beginTransaction();

            $image = $request->file('image');
            $attr['image'] = $image->storeAs('images/device', 'dev' . date('Ymd') . rand(1000, 9999) . '.' . $image->extension());

            $device = Device::create($attr);
            $modbuses = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16];
            $digital = [1, 2, 3, 4, 5, 6, 7,];

            foreach ($modbuses as $modbus) {
                $device->modbuses()->create([
                    'name' => 'Modbus ' . $modbus,
                ]);
            }

            foreach ($digital as $dig) {
                $device->digitalInputs()->create([
                    'name' => 'Digital Input ' . $dig,
                    'digital_input' => $dig
                ]);
            }

            DB::commit();

            return redirect()->route('device.index')->with('success', 'Device sucessfully created');
        } catch (\Throwable $th) {
            DB::rollBack();
            return back()->with('error', $th->getMessage());
        }
    }

    public function show(Device $device)
    {
        $apikey = SecretKey::findOrFail(2)->key;

        return view('device.show', compact('device', 'apikey'));
    }

    public function edit(Device $device)
    {
        $this->middleware('admin');

        $action = route('device.update', $device->id);
        $act = 'edit';

        return view('device.form', compact('device', 'action', 'act'));
    }

    public function update(Request $request, Device $device)
    {
        $this->middleware('admin');

        $attr = $request->validate([
            'name' => 'required|string',
            'end_user' => 'required|string',
            'iddev' => 'required|unique:devices,iddev,' . $device->iddev,
            'type' => 'required|string',
            'power' => 'required|string',
            'flow' => 'required|string',
            'head' => 'required|string',
            'modbus' => 'required|string',
            'digital' => 'required|string',
            'lat' => 'required|string',
            'long' => 'required|string',
            'image' => 'mimes:jpg,jpeg,png',
        ]);

        try {
            DB::beginTransaction();

            if ($request->file('image')) {
                Storage::delete($device->image);
                $image = $request->file('image');
                $attr['image'] = $image->storeAs('images/device', 'dev' . date('Ymd') . rand(1000, 9999) . '.' . $image->extension());
            } else {
                $attr['image'] = $device->image;
            }

            $device->update($attr);

            DB::commit();

            return redirect()->route('device.index')->with('success', 'Device sucessfully updated');
        } catch (\Throwable $th) {
            DB::rollBack();
            return back()->with('error', $th->getMessage());
        }
    }

    public function destroy(Device $device)
    {
        $this->middleware('admin');

        try {
            DB::beginTransaction();
            foreach ($device->histories as $history) {
                $history->delete();
            }

            foreach ($device->modbuses as $modbus) {
                $modbus->delete();
            }

            foreach ($device->digitalInputs as $digital) {
                $digital->delete();
            }

            $device->delete();

            DB::commit();

            return back()->with('success', 'Device successfully deleted');
        } catch (\Throwable $th) {
            DB::rollBack();
            return back()->with('error', $th->getMessage());
        }
    }

    public function get()
    {
        if (auth()->user()->level == 'Viewer') {
            $user = User::find(auth()->user()->id);
            $first = $user->devices()->first();
            if ($first) {
                $devices = $user->devices;
            } else {
                $devices = '';
            }
        } else {
            $first = Device::where('is_active', 1)->first();
            if ($first) {
                $devices = Device::where('is_active', 1)->get();
            } else {
                $devices = '';
            }
        }

        return response()->json([
            'devices' => $devices
        ]);
    }

    public function find(Device $device)
    {
        $modbus = $device->modbuses()->where('is_used', 1)->get();
        $digital = $device->digitalInputs()->where('is_used', 1)->get();
        $image = asset('/storage/' . $device->image);
        $history = $device->histories()->latest()->first();
        $merge = Merge::where('device_id', $device->id)->get();

        return response()->json([
            'device' => $device,
            'modbus' => $modbus,
            'digital' => $digital,
            'merge' => $merge,
            'image' => $image,
            'history' => $history ? Carbon::parse($history->created_at)->format('d/m/Y H:i:s') : '-',
        ]);
    }

    public function math(Request $request)
    {
        try {
            DB::beginTransaction();
            $modbus = Modbus::find($request->id);

            $modbus->update([
                'math' => '',
            ]);

            $modbus->update([
                'math' => $request->math,
                'after' => $request->after,
            ]);


            History::create([
                'device_id' => $modbus->device->id,
                'val' => $request->after,
                'ket' => 'Math ' . $modbus->name
            ]);

            DB::commit();

            return response()->json([
                'status' => 'success',
                'message' => 'Value modbus successfully updated'
            ]);
        } catch (\Throwable $th) {
            return response()->json([
                'status' => 'error',
                'message' => $th->getMessage()
            ]);
        }
    }

    public function active()
    {
        try {
            DB::beginTransaction();

            $device = Device::find(request('id'));
            $device->update([
                'is_active' => request('active')
            ]);

            if (request('active') == 1) {
                $message = 'Device successfully activated';
            } else {
                $message = 'Device successfully non activated';
            }

            DB::commit();

            return response()->json([
                'status' => 'success',
                'message' => $message
            ]);
        } catch (\Throwable $th) {
            DB::rollBack();
            return response()->json([
                'status' => 'error',
                'message' => $th->getMessage()
            ]);
        }
    }

    public function history(Device $device)
    {
        $modbus = History::with('modbus')->where('device_id', $device->id)->where('modbus_id', '!=', 0)->latest()->get();
        $digital = History::with('digital')->where('device_id', $device->id)->where('digital_input_id', '!=', 0)->latest()->get();

        return response()->json([
            'device' => $device,
            'modbus' => $modbus,
            'digital' => $digital,
        ]);
    }

    public function historyModbus(Device $device)
    {
        if (request('from') != '' && request('to') != '') {
            $active = Modbus::where('device_id', $device->id)->where('is_showed', 1)->whereHas('histories', function ($q) {
                $q->whereBetween('created_at', [request('from'), Carbon::parse(request('to'))->addDay(1)->format('Y-m-d')]);
            })->with('histories', function ($q) {
                $q->whereBetween('created_at', [request('from'), Carbon::parse(request('to'))->addDay(1)->format('Y-m-d')]);
            })->latest()->get();
        } else {
            $count = Modbus::where('device_id', $device->id)->where('is_showed', 1)->count();
            $total = $count * 10;

            $active = Modbus::where('device_id', $device->id)->where('is_showed', 1)->with('histories', function ($q) use ($total) {
                $q->latest()->limit($total);
            })->whereHas('histories', function ($q) use ($total) {
                $q->latest()->limit($total);
            })->get();

            $digital = DigitalInput::where('device_id', $device->id)->where('is_used', 1)->get();
            $modbus = Modbus::where('device_id', $device->id)->where('is_used', 1)->get();
            $history = History::where('device_id', $device->id)->groupBy('time')->limit(10)->latest()->get();
        }

resources/views/device/form.blade.php
@extends('layouts.master', ['title' => $act == 'create' ? 'Create Device' : 'Edit Device'])

@section('content')
<div class="row">
    <div class="col-md-12">
        @if($act == 'create')
        <h2 class="mb-3 lh-sm">Create Device</h2>
        @else
        <h2 class="mb-3 lh-sm">Edit Device</h2>
        @endif

        <form action="{{ $action }}" method="post" enctype="multipart/form-data">
            @if($act == 'edit')
            @method('PATCH')
            @endif
            @csrf

            <div class="form-group row mb-3">
                <div class="col-md-6">
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" class="form-control" value="{{ $device->name ?? old('name') }}">

                    @error('name')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="col-md-6">
                    <label for="iddev">ID Device</label>
                    <input type="text" name="iddev" id="iddev" class="form-control" value="{{ $device->iddev ?? old('iddev') }}">

                    @error('iddev')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-md-6">
                    <label for="end_user">End User</label>
                    <input type="text" name="end_user" id="end_user" class="form-control" value="{{ $device->end_user ?? old('end_user') }}">

                    @error('end_user')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="col-md-6">
                    <label for="lat">Latitude</label>
                    <input type="text" name="lat" id="lat" class="form-control" value="{{ $device->lat ?? old('lat') }}">

                    @error('lat')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>
            </div>


            <div class="form-group mb-3 row">
                <div class="col-md-6">
                    <label for="type">Type</label>
                    <input type="text" name="type" id="type" class="form-control" value="{{ $device->type ?? old('type') }}">

                    @error('type')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="col-md-6">
                    <label for="long">Longitude</label>
                    <input type="text" name="long" id="long" class="form-control" value="{{ $device->long ?? old('long') }}">

                    @error('long')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-md-6">
                    <label for="power">Power</label>
                    <input type="text" name="power" id="power" class="form-control" value="{{ $device->power ?? old('power') }}">

                    @error('type')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="col-md-6">
                    <label for="modbus">Title Modbus</label>
                    <input type="text" name="modbus" id="modbus" class="form-control" value="{{ $device->modbus ?? old('modbus') }}" placeholder="Pump Status">

                    @error('modbus')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-md-6">
                    <label for="head">Head</label>
                    <input type="text" name="head" id="head" class="form-control" value="{{ $device->head ?? old('head') }}">

                    @error('head')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="col-md-6">
                    <label for="digital">Title Digital Input</label>
                    <input type="text" name="digital" id="digital" class="form-control" value="{{ $device->digital ?? old('digital') }}" placeholder="Pump Status">

                    @error('digital')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>
            </div>

            <div class="form-group row mb-3">
                <div class="col-md-6">
                    <label for="flow">Flow</label>
                    <input type="text" name="flow" id="flow" class="form-control" value="{{ $device->flow ?? old('flow') }}">

                    @error('flow')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="col-md-6">
                    <label for="image">Image</label>
                    <input type="file" name="image" id="image" class="form-control">

                    @error('image')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>
            </div>

            <div class="form-group mb-3">
                <button type="submit" class="btn btn-success mt-3">Submit</button>
            </div>
        </form>
    </div>
</div>
@stop

resources/views/device/index.blade.php
@extends('layouts.master', ['title' => 'Data Device'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <h2 class="mb-3 lh-sm">Data Device</h2>

        <div id="tableExample2" data-list='{"valueNames":["no","img","name","id","type","lat","long","is_active", "action"],"page":10,"pagination":true}'>

            @if(auth()->user()->level == 'Admin')
            <a href="{{ route('device.create') }}" class="btn btn-sm btn-success mb-3">Add Device</a>
            @endif

            <div class="table-responsive scrollbar">
                <table class="table table-bordered table-striped fs--1 mb-0">
                    <thead class="bg-200 text-900">
                        <tr>
                            <th class="sort" data-sort="no">No</th>
                            <th class="sort" data-sort="img">Image</th>
                            <th class="sort" data-sort="id">Id Device</th>
                            <th class="sort" data-sort="name">Name</th>
                            <th class="sort" data-sort="type">Type</th>
                            <th class="sort" data-sort="lat">Lat</th>
                            <th class="sort" data-sort="long">Long</th>
                            <th class="sort" data-sort="action">Action</th>
                            <th class="sort" data-sort="is_active">Active</th>
                        </tr>
                    </thead>
                    <tbody class="list">
                        @foreach($devices as $device)
                        <tr>
                            <td class="no">{{ $loop->iteration }}</td>
                            <td class="img"><img src="{{ asset('/storage/'.$device->image) }}" alt="" width="70px"></td>
                            <td class="id">{{ $device->iddev }}</td>
                            <td class="name">{{ $device->name }}</td>
                            <td class="type">{{ $device->type }}</td>
                            <td class="lat">{{ $device->lat }}</td>
                            <td class="long">{{ $device->long }}</td>
                            <td class="action">
                                <a href="{{ route('device.show', $device->id) }}" title="Show Device" class="btn btn-sm btn-secondary mr-2"><i class="fas fa-eye"></i></a>

                                <a href="{{ route('device.grafik', $device->id) }}" title="Grafik Device" class="btn btn-sm btn-warning mr-2"><i class="fas fa-chart-line"></i></a>

                                <a href="{{ route('device.edit', $device->id) }}" title="Edit Device" class="btn btn-sm btn-info mr-2"><i class="fas fa-edit"></i></a>

                                <a href="{{ route('device.reset', $device->id) }}" title="Reset Device" class="btn btn-sm btn-success mr-2" onclick="return confirm('Reset device ?')"><i class="fas fa-sync"></i></a>

                                <form action="{{ route('device.destroy', $device->id) }}" method="post" style="display: inline;">
                                    @method('DELETE')
                                    @csrf

                                    <button type="submit" title="Delete Device" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure delete this data?')"><i class="fas fa-trash"></i></button>
                                </form>
                            </td>
                            <td class="is_active">
                                <div class="form-check form-switch">
                                    <input class="form-check-input device-active" data-id="{{ $device->id }}" type="checkbox" name="active" {{ $device->is_active == 1 ? 'checked' : '' }}>
                                    <label class="form-check-label label-{{ $device->id }}" for="active">{{ $device->is_active == 1 ? 'Active' : 'Nonactive' }}</label>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="d-flex justify-content-center mt-3">
                <button class="btn btn-sm btn-falcon-default me-1" type="button" title="Previous" data-list-pagination="prev"><span class="fas fa-chevron-left"></span></button>
                <ul class="pagination mb-0"></ul>
                <button class="btn btn-sm btn-falcon-default ms-1" type="button" title="Next" data-list-pagination="next"><span class="fas fa-chevron-right"></span></button>
            </div>
        </div>
    </div>
</div>
@stop

@push('script')
<script src="{{ asset('/js/script.js') }}"></script>
@endpush